top_modules:
    - fastqc:
        name: 'FastQC (cutadapt filtered)'
        info: 'This section of the report shows FastQC results after sickle filtering.'
        target: ''
        path_filters:
            - '*trans_trim_fastqc.zip'
    - cutadapt:
        name: 'Cutadapt'
        info: 'This sectino of the report shows cutadapt log reports'
        target: ''
        path_filters:
            - '*_cutadapt.log'
    - fastqc:
        name: 'FastQC (raw)'
        path_filters:
            - '*1_fastqc.zip'
